#ifndef GLEXT_H_INCLUDED
#define GLEXT_H_INCLUDED

#include <GL/gl.h>
#include <GL/glext.h>

void init_gl_extensions();
void init_gl_extensions_ARB();

PFNGLUSEPROGRAMPROC          glUseProgram;
PFNGLCREATESHADERPROC        glCreateShader;
PFNGLSHADERSOURCEPROC        glShaderSource;
PFNGLCOMPILESHADERPROC       glCompileShader;
PFNGLCREATEPROGRAMPROC       glCreateProgram;
PFNGLLINKPROGRAMPROC         glLinkProgram;
PFNGLATTACHSHADERPROC        glAttachShader;
PFNGLGENBUFFERSPROC          glGenBuffers;
PFNGLBINDBUFFERPROC          glBindBuffer;
PFNGLBUFFERDATAPROC          glBufferData;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;

PFNGLENABLEVERTEXATTRIBARRAYPROC  glEnableVertexAttribArray;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;

PFNGLUNIFORM1FPROC        glUniform1f;
PFNGLUNIFORM2FPROC        glUniform2f;
PFNGLUNIFORM3FPROC        glUniform3f;
PFNGLUNIFORM4FPROC        glUniform4f;
PFNGLUNIFORM1IPROC        glUniform1i;
PFNGLUNIFORM2IPROC        glUniform2i;
PFNGLUNIFORM3IPROC        glUniform3i;
PFNGLUNIFORM4IPROC        glUniform4i;
PFNGLUNIFORM1FVPROC       glUniform1fv;
PFNGLUNIFORM2FVPROC       glUniform2fv;
PFNGLUNIFORM3FVPROC       glUniform3fv;
PFNGLUNIFORM4FVPROC       glUniform4fv;
PFNGLUNIFORM1IVPROC       glUniform1iv;
PFNGLUNIFORM2IVPROC       glUniform2iv;
PFNGLUNIFORM3IVPROC       glUniform3iv;
PFNGLUNIFORM4IVPROC       glUniform4iv;

PFNGLCREATESHADEROBJECTARBPROC    glCreateShaderObjectARB;
PFNGLSHADERSOURCEARBPROC        glShaderSourceARB;
PFNGLCOMPILESHADERARBPROC      glCompileShaderARB;
PFNGLCREATEPROGRAMOBJECTARBPROC    glCreateProgramObjectARB;
PFNGLATTACHOBJECTARBPROC        glAttachObjectARB;
PFNGLDETACHOBJECTARBPROC        glDetachObjectARB;
PFNGLLINKPROGRAMARBPROC        glLinkProgramARB;
PFNGLUSEPROGRAMOBJECTARBPROC      glUseProgramObjectARB;
PFNGLDELETEOBJECTARBPROC        glDeleteObjectARB;
PFNGLUNIFORM1FARBPROC        glUniform1fARB;
PFNGLUNIFORM2FARBPROC        glUniform2fARB;
PFNGLUNIFORM3FARBPROC        glUniform3fARB;
PFNGLUNIFORM4FARBPROC        glUniform4fARB;
PFNGLUNIFORM1IARBPROC        glUniform1iARB;
PFNGLUNIFORM2IARBPROC        glUniform2iARB;
PFNGLUNIFORM3IARBPROC        glUniform3iARB;
PFNGLUNIFORM4IARBPROC        glUniform4iARB;
PFNGLUNIFORM1FVARBPROC        glUniform1fvARB;
PFNGLUNIFORM2FVARBPROC        glUniform2fvARB;
PFNGLUNIFORM3FVARBPROC        glUniform3fvARB;
PFNGLUNIFORM4FVARBPROC        glUniform4fvARB;
PFNGLUNIFORM1IVARBPROC        glUniform1ivARB;
PFNGLUNIFORM2IVARBPROC        glUniform2ivARB;
PFNGLUNIFORM3IVARBPROC        glUniform3ivARB;
PFNGLUNIFORM4IVARBPROC        glUniform4ivARB;
PFNGLUNIFORMMATRIX2FVARBPROC      glUniformMatrix2fvARB;
PFNGLUNIFORMMATRIX3FVARBPROC      glUniformMatrix3fvARB;
PFNGLUNIFORMMATRIX4FVARBPROC      glUniformMatrix4fvARB;
PFNGLGETOBJECTPARAMETERFVARBPROC    glGetObjectParameterfvARB;
PFNGLGETOBJECTPARAMETERIVARBPROC    glGetObjectParameterivARB;
PFNGLGETINFOLOGARBPROC        glGetInfoLogARB;
PFNGLGETATTACHEDOBJECTSARBPROC    glGetAttachedObjectsARB;
PFNGLGETUNIFORMLOCATIONARBPROC    glGetUniformLocationARB;
PFNGLGETACTIVEUNIFORMARBPROC      glGetActiveUniformARB;
PFNGLGETUNIFORMFVARBPROC        glGetUniformfvARB;
PFNGLGETUNIFORMIVARBPROC        glGetUniformivARB;
PFNGLGETSHADERSOURCEARBPROC      glGetShaderSourceARB;

#endif // GLEXT_H_INCLUDED
